# Site settings
title: My network Blog Title
author:
  name: tou you
  email: your-email@domain.com
description: "My site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
url: 'https://said120276.github.io/' # your main domain
baseurl: 'first-blog/' # if you're using custom domain keep this blank example: baseurl: ''
